server:
  port: 8000

spring:
  application:
    name: customer-service
  datasource:
    username: 'luv4code'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
