server:
  port: 8001

spring:
  application:
    name: fraud-service
  datasource:
    username: 'luv4code'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/fraud
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
